"$schema" = 'https://starship.rs/config-schema.json'

gcloud.disabled = true
docker_context.disabled = true
golang.disabled = true
nodejs.disabled = true
php.disabled = true
lua.disabled = true
package.disabled = true

